---
- name: Install Apache and modules.
  dnf:
    name: "{{ item }}"
    state: installed
  with_items:
    - httpd
    - httpd-devel
    - mod_ssl
    - openssh

# apache configuration:
- include: config.yml
