---
- hosts: vagrant
  sudo: true
  vars_files:
    - vars/all.yml
  gather_facts: false # Fedora23 doesn't have python2 installed by default
  roles:
    - ansible_prepare # prepare remote box for ansible provisioning
    - server
    - handy_soft
    - apache
    - php
