---
- hosts: vagrant
  sudo: true
  vars_files:
    - vars/all.yml
  gather_facts: false # Fedora23 doesn't have python2 installed by default
  roles:
    - python2
    - facts   # gather facts manualy after python2 is properly installed
    - server
    - handy_soft
    - apache
    - php
